### ISSUE TITLE
import { Fountain } from 'fountain' doesn't work

### ISSUE THREAD

**Issue by pjebs** [jonnygreenwald/Fountain.ts#8]
I ran `npm install  fountain`
and then `import { Fountain } from 'fountain'`

```
[plugin vite:dep-scan] Failed to resolve entry for package "fountain". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "fountain". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:10:
      29537 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (/Users/pj/software/petersir/sveltekit/node_modules/vite/dist/node/chunks/dep-9c153816.js:29537:11)
    at resolvePackageEntry (/Users/pj/software/petersir/sveltekit/node_modules/vite/dist/node/chunks/dep-9c153816.js:29533:9)
    at tryNodeResolve (/Users/pj/software/petersir/sveltekit/node_modules/vite/dist/node/chunks/dep-9c153816.js:29349:20)
    at Context.resolveId (/Users/pj/software/petersir/sveltekit/node_modules/vite/dist/node/chunks/dep-9c153816.js:29166:28)
    at Object.resolveId (/Users/pj/software/petersir/sveltekit/node_modules/vite/dist/node/chunks/dep-9c153816.js:38271:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/Users/pj/software/petersir/sveltekit/node_modules/vite/dist/node/chunks/dep-9c153816.js:38474:26)
    at async /Users/pj/software/petersir/sveltekit/node_modules/vite/dist/node/chunks/dep-9c153816.js:38612:34
    at async callback (/Users/pj/software/petersir/sveltekit/node_modules/esbuild/lib/main.js:917:28)
    at async handleRequest (/Users/pj/software/petersir/sveltekit/node_modules/esbuild/lib/main.js:697:30)

  This error came from the "onResolve" callback registered here:
```

**Comment by pjebs** [comment]
I'm trying to import it to a browser-based SvelteKit JS project.

**Comment by jonnygreenwald** [comment]
I'm looking into this, but just as an update for you.

I ran my tests against Node `v16.14.0` and they all came out passing. In fact I did a bit of upgrading to the testing suite just because there were some deprecated methods in there and everything still appears to be working fine.

Reading into this, this seems to be a fairly common issue in Vite and I did find [references](https://github.com/frandiox/reactesse-edge-template/issues/5) that indicated using older versions of Vite like 2.7x could help resolve this issue in the meantime.

Ultimately, it does seem like its something missing in my package like perhaps the `modules` field as best I can tell.

Overall, I am still fairly new to all of this so I'm going to keep digging into this and let you know once I get something solid to work with.

**Comment by pjebs** [comment]
I don't think the new version is registered with npm.

**Comment by jonnygreenwald** [comment]
Apologies, I just meant that I updated my testing suite earlier, which would have not gone to NPM; however, I have _just_ published `v0.1.3` and will hopefully be up shortly.

**Comment by pjebs** [comment]
The issue was `npm i fountain.ts` (not npm i fountain) and also importing `fountain.ts` (not `fountain`)
`import from 'fountain'` is a totally different package.

**Comment by jonnygreenwald** [comment]
Yup! I just realized my README was wrong too. 🤦‍♀️ 

This is now updated.
